<entries>
   <write addr="1" val="0" />
   <write addr="2" val="0" />
   <write addr="3" val="0" />
   <write addr="4" val="0" />
   <write addr="5" val="0" />
   <write addr="6" val="0" />
   <write addr="7" val="0" />
   <write addr="8" val="0" />
   <write addr="9" val="880" />
   <write addr="10" val="0" />
   <write addr="11" val="0" />
   <write addr="12" val="0" />
   <write addr="13" val="0" />
   <write addr="14" val="0" />
</entries>
